### ISSUE TITLE
raw model not working with `load`, only with `loads`

### ISSUE THREAD

**Issue by FlorianLudwig** [spyoungtech/json-five#30]
https://json-five.readthedocs.io/en/latest/comments.html

works as expected:
```
model = json5.loader.loads(json_string, loader=ModelLoader())
```

does not work as expected:
```
model = json5.loader.load(json_fd, loader=ModelLoader())
```

**Comment by spyoungtech** [comment]
Fix for this has now been released in v0.7.5 🎉 Thanks @FlorianLudwig
